### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ilarijn** [lauriap/random-dungeons#1]
Työ oli oikein huolellisesti dokumentoitu, koodi kommentoitua ja selkeästi jäsenneltyä, eikä työtä tarkastellessa ollut mitään rakenteesta tai dokumentaatiosta johtuneita ongelmia saada ajatuksesta kiinni. Testejäkin oli todella kiitettävästi.

Kummankin karttatyypin oikea reuna generoituu epätasaisesti, ts. toiseen laitaan jää paljon käyttämätöntä tilaa. Ehkä kartasta voisi tehdä suuremman kuin tarvitsee, ja esimerkiksi lisätä sitten tulostusvaiheessa laitaan seinää? Tein itse hieman vastaavalla tavalla työssäni tilanteessa jossa täytyy tulostaa neliskulmainen kartta suorakaiteen muotoiseen ikkunaan. 

Jos nyt jotain huomautettavaa pitää vielä keksiä, niin en pidä tarpeellisena aivan jokaisen getter- ja setter- yms. metodin perusteellista kommentointia. Itsestäänselvien toimintojen kohdalla ylimääräinen teksti ei oikeastaan helpota koodin lukemista. Tämä on toisaalta makuasia, enkä itse asiassa edes tiedä, oletetaanko kurssin arvostelussa näin tehtävän.

Jos aikaa ja intoa riittää niin reitinhakualgoritmilla saisi työhön tosiaan vielä bonuksena quick travel -ominaisuuden generoituihin karttoihin. :) Tsemppiä viimeisille viikoille!

Koodikatselmointi tehty 14/02/2020 15:09 kloonatun aineiston perusteella.

**Comment by lauriap** [comment]
Kiitos kommentista! Kartan tulostumiseen liittyviä ongelmia ajattelinkin tulevalla viikolla hieman pohtia. Otan ideasi harkintaa.

Kiitos samoin sinne!
