### ISSUE TITLE
Koodikatselmointi #2

### ISSUE THREAD

**Issue by Roeoeri** [lauriap/random-dungeons#2]
# Koodikatselmointi 2

### Katselmoitu 29.2 klo 1:00

Aloitin katselmoinnin ajamalla Buildin ja Testit. Molemmat menivät hienosti läpi, joskin buildissa oli hieman checkstylevirheitä (niin kuin vielä tässä vaiheessa on kaikilla), mutta checkstylevirheet kannattaa korjata ennen viimeistä palautusta. Toivoisin tosin, että loisit gradleen oman run taskin, mikä mahdollistaisi projektin ajamisen suoraan komentoriviltä ilman netbeanssia.

Projekti näyttää rakenteeltaan oikein hyvältä. Koodi on siistiä ja erittäin hyvin kommentoitua. Pienenä huomiona mainitsisin että koodissa on jonkin verran taikanumeroita, eli numeroarvoja, joiden tarkoitusta ei ole sen tarkemmin avattu. Voisit ehkä sijoittaa kyseiset arvot muuttujiin jotka ilmaisevat nimensä kautta arvojen käyttötarkoituksen. 

Muuta huomioitavaa en projektista oikein keksinyt. Projektisi on erittäin hyvällä mallilla ja hienosti tehty.

**Comment by lauriap** [comment]
Kiitos palautteesta! Otan nämä huomioon työtä viimeistellessäni.

Tsemppiä loppuprojektiin!
